const data = {
  services: [
    {
      title: "SERVICIO DOMICILIO 🏠",
      list: [
        "Trámites legales ante las autoridades competentes  para la inhumación",
        "Legalización de certificado de defuncion ",
        "Certificado de Defuncion debidamente legalizado",
        "Traslados a las salas de velación y al camposanto respectivamente en (1) autocarroza de LUJO",
        "Carroza para el transporte de flores",
        "Proveer al cliente de un cofre de PRIMERA",
        "Sábana Santa",
        "Servicio completo de Tanatopraxia",
        "Formolización por 24 horas",
        "Capilla ardiente completa",
        "Aviso NECROLOGICO virtual / obituario",
        "Entrega de un libro de condolencias con aspectos relacionados a las honras fúnebres",
      ],
      price: "4,490 BOB",
    },
    {
      title: "SERVICIO EXPRESS ⏩",
      list: [
        "Trámites legales ante las autoridades competentes  para la inhumación",
        "Traslados del cuerpo ((2) no en carroza funebre)",
        "Proveer al cliente de un cofre  ELEMENTAL o ECOLOGICO",
        "Servicio completo de Tanatopraxia",
        "Formolización por 24 horas",
        "Personal uniformado para la atención",
      ],
      price: "3,690 BOB",
    },
    {
      title: "SERVICIO ECOLÓGICO 🌲",
      list: [
        "Legalización Certificado de OBITO",
        "Traslados a las salas de velación y al camposanto respectivamente en (1) autocarroza",
        "Proveer al cliente de un cofre ELEMENTAL",
        "Sábana Santa",
        "Servicio completo de Tanatopraxia",
        "Formolización por 24 horas",
        "Salón de velación por 24 horas con A/C",
        "Música ambiental durante el servicio",
        "Capilla ardiente completa",
        "Servicio de cafetería básica (hasta 2 AM)",
        "Aviso NECROLOGICO virtual / obituario",
        "Personal uniformado para la atención",
      ],
      offerList: [
        "Legalización Certificado de OBITO",
        "Traslados a las salas de velación y al camposanto respectivamente en (1) autocarroza",
        "Proveer al cliente de un cofre ECOLÓGICO",
        "Sábana Santa",
        "Servicio completo de Tanatopraxia",
        "Formolización por 24 horas",
        "Salón de velación por 24 horas con A/C",
        "Música ambiental durante el servicio",
        "Capilla ardiente completa",
        "Servicio de cafetería básica (hasta 2 AM)",
        "Aviso NECROLOGICO virtual / obituario",
        "Personal uniformado para la atención",
      ],
      price: "6,990 BOB",
      offerPrice: "5,990 BOB",
    },
    {
      title: "SERVICIO ÉLITE 👔",
      list: [
        "Trámites legales ante las autoridades competentes para la inhumación",
        "Legalización del Certificado de OBITO",
        "Certificado de DEFUNCION debidamente legalizado",
        "Traslados a las salas de velación y al camposanto respectivamente en (1) autocarroza de LUJO",
        "Traslado de flores en una carroza ",
        "Proveer al cliente de un cofre de PRIMERA",
        "Sábana Santa",
        "Servicio completo de Tanatopraxia",
        "Formolización por 24 horas",
        "Salón de velación por 24 horas con A/C",
        "Música ambiental durante el servicio",
        "Capilla ardiente completa",
        "Servicio de cafetería con atención permanente 24 horas",
        "Servicio de garzones 1 turno",
        "Personal uniformado para la atención",
        "Aviso NECROLOGICO virtual / obituario",
        "Entrega de un libro de condolencias con aspectos relacionados a las honras fúnebres",
      ],
      offerList: [
        "Trámites legales ante las autoridades competentes para la inhumación",
        "Legalización del Certificado de OBITO",
        "Certificado de DEFUNCION debidamente legalizado",
        "Traslados a las salas de velación y al camposanto respectivamente en (1) autocarroza de LUJO",
        "Traslado de flores en una carroza ",
        "Proveer al cliente de un cofre de ECOLÓGICO",
        "Sábana Santa",
        "Servicio completo de Tanatopraxia",
        "Formolización por 24 horas",
        "Salón de velación por 24 horas con A/C",
        "Música ambiental durante el servicio",
        "Capilla ardiente completa",
        "Servicio de cafetería con atención permanente 24 horas",
        "Servicio de garzones 1 turno",
        "Personal uniformado para la atención",
        "Aviso NECROLOGICO virtual / obituario",
        "Entrega de un libro de condolencias con aspectos relacionados a las honras fúnebres",
      ],
      price: "9,990 BOB",
      offerPrice: "7,990 BOB",
    },
    {
      title: "SERVICIO CROWN 👑",
      list: [
        "Trámites legales ante las autoridades competentes para la inhumación",
        "Legalización del Certificado de OBITO",
        "Certificado de DEFUNCION debidamente legalizado",
        "Traslados a las salas de velación y al camposanto respectivamente en (1) autocarroza de LUJO",
        "Traslado de flores en una carroza ",
        "Proveer al cliente de un cofre de PRIMERA",
        "Sábana Santa",
        "Servicio completo de Tanatopraxia",
        "Formolización por 24 horas",
        "Salón de velación por 24 horas con A/C",
        "Música ambiental durante el servicio",
        "Decoración de la sala de velación con sus (3)",
        "Celebración del servicio religioso a cargo de un ministro del culto indicado por el cliente",

        "Capilla ardiente completa",
        "Servicio de cafetería con atención permanente 24 horas",
        "Servicio de garzones 1 turno",
        "Suite para descanso con baño privado",
        "Habilitacion de Terraza, jardines y pileta",
        "Protocolo VIP para la atención del servicio",
        "Personal uniformado para la atención",
        "Aviso NECROLOGICO virtual / obituario",
        "Entrega de un libro de condolencias con aspectos relacionados a las honras fúnebres",
        "Tarjetas de agradecimiento",
        "Transporte al cementerio en un MICRO",
      ],
      offerList: [
        "Trámites legales ante las autoridades competentes para la inhumación",
        "Legalización del Certificado de OBITO",
        "Certificado de DEFUNCION debidamente legalizado",
        "Traslados a las salas de velación y al camposanto respectivamente en (1) autocarroza de LUJO",
        "Traslado de flores en una carroza ",
        "Proveer al cliente de un cofre de ECOLÓGICO",
        "Sábana Santa",
        "Servicio completo de Tanatopraxia",
        "Formolización por 24 horas",
        "Salón de velación por 24 horas con A/C",
        "Música ambiental durante el servicio",
        "Decoración de la sala de velación con sus (3)",
        "Celebración del servicio religioso a cargo de un ministro del culto indicado por el cliente",

        "Capilla ardiente completa",
        "Servicio de cafetería con atención permanente 24 horas",
        "Servicio de garzones 1 turno",
        "Suite para descanso con baño privado",
        "Habilitacion de Terraza, jardines y pileta",
        "Protocolo VIP para la atención del servicio",
        "Personal uniformado para la atención",
        "Aviso NECROLOGICO virtual / obituario",
        "Entrega de un libro de condolencias con aspectos relacionados a las honras fúnebres",
        "Tarjetas de agradecimiento",
        "Transporte al cementerio en un MICRO",
      ],
      price: "12,990 BOB",
      offerPrice: "10,990 BOB",
    },
    {
      title: "SERVICIO ROYAL 🏰",
      list: [
        "Trámites legales ante las autoridades competentes para la inhumación",
        "Legalización del Certificado de OBITO",
        "Certificado de DEFUNCION debidamente legalizado",
        "Traslados a las salas de velación y al camposanto respectivamente en (1) autocarroza de LUJO",
        "Traslado de flores en una carroza ",
        "Proveer al cliente de un cofre de LUXOR",
        "Sábana Santa",
        "Servicio completo de Tanatopraxia",
        "Formolización por 24 horas",
        "Salón de velación por 24 horas con A/C",
        "Música ambiental durante el servicio",
        "Decoración de la sala de velación con sus (3)",
        "Celebración del servicio religioso a cargo de un ministro del culto indicado por el cliente",
        "Capilla ardiente completa",
        "Servicio de cafetería con atención permanente 24 horas",
        "Servicio de garzones 2 turnos",
        "Suite para descanso con baño privado",
        "Habilitacion de Terraza, jardines y pileta",
        "Protocolo VIP para la atención del servicio",
        "Personal uniformado para la atención",
        "Aviso NECROLOGICO virtual / obituario",
        "Entrega de un libro de condolencias con aspectos relacionados a las honras fúnebres",
        "Tarjetas de agradecimiento",
      ],
      offerList: [
        "Trámites legales ante las autoridades competentes para la inhumación",
        "Legalización del Certificado de OBITO",
        "Certificado de DEFUNCION debidamente legalizado",
        "Traslados a las salas de velación y al camposanto respectivamente en (1) autocarroza de LUJO",
        "Traslado de flores en una carroza ",
        "Proveer al cliente de un cofre de ECOLÓGICO",
        "Sábana Santa",
        "Servicio completo de Tanatopraxia",
        "Formolización por 24 horas",
        "Salón de velación por 24 horas con A/C",
        "Música ambiental durante el servicio",
        "Decoración de la sala de velación con sus (3)",
        "Celebración del servicio religioso a cargo de un ministro del culto indicado por el cliente",
        "Capilla ardiente completa",
        "Servicio de cafetería con atención permanente 24 horas",
        "Servicio de garzones 2 turnos",
        "Suite para descanso con baño privado",
        "Habilitacion de Terraza, jardines y pileta",
        "Protocolo VIP para la atención del servicio",
        "Personal uniformado para la atención",
        "Aviso NECROLOGICO virtual / obituario",
        "Entrega de un libro de condolencias con aspectos relacionados a las honras fúnebres",
        "Tarjetas de agradecimiento",
      ],
      price: "15,990 BOB",
      offerPrice: "13,990 BOB",
    },
    {
      title: "SERVICIO PLATINUM ⬜",
      list: [
        "Trámites legales ante las autoridades competentes para la inhumación",
        "Legalización del Certificado de OBITO",
        "Certificado de DEFUNCION debidamente legalizado",
        "Traslados a las salas de velación y al camposanto respectivamente en (1) autocarroza de LUJO",
        "Traslado de flores en una carroza ",
        "Proveer al cliente de un cofre de LUXOR",
        "Sábana Santa",
        "Servicio completo de Tanatopraxia",
        "Formolización por 24 horas",
        "Salón de velación por 24 horas con A/C",
        "Música ambiental durante el servicio",
        "Decoración de la sala de velación con sus (5)",
        "Celebración del servicio religioso a cargo de un ministro del culto indicado por el cliente",
        "Capilla ardiente completa",
        "Servicio de cafetería con atención permanente 24 horas",
        "Servicio de garzones 2 turnos",
        "Suite para descanso con baño privado",
        "Habilitacion de Terraza, jardines y pileta",
        "Protocolo VIP para la atención del servicio",
        "Personal uniformado para la atención",
        "Aviso NECROLOGICO virtual / obituario",
        "Entrega de un libro de condolencias con aspectos relacionados a las honras fúnebres",
        "Tarjetas de agradecimiento",
      ],
      offerList: [
        "Trámites legales ante las autoridades competentes para la inhumación",
        "Legalización del Certificado de OBITO",
        "Certificado de DEFUNCION debidamente legalizado",
        "Traslados a las salas de velación y al camposanto respectivamente en (1) autocarroza de LUJO",
        "Traslado de flores en una carroza ",
        "Proveer al cliente de un cofre de ECOLÓGICO",
        "Sábana Santa",
        "Servicio completo de Tanatopraxia",
        "Formolización por 24 horas",
        "Salón de velación por 24 horas con A/C",
        "Música ambiental durante el servicio",
        "Decoración de la sala de velación con sus (5)",
        "Celebración del servicio religioso a cargo de un ministro del culto indicado por el cliente",
        "Capilla ardiente completa",
        "Servicio de cafetería con atención permanente 24 horas",
        "Servicio de garzones 4 turnos",
        "Suite para descanso con baño privado",
        "Habilitacion de Terraza, jardines y pileta",
        "Protocolo VIP para la atención del servicio",
        "Personal uniformado para la atención",
        "Aviso NECROLOGICO virtual / obituario",
        "Entrega de un libro de condolencias con aspectos relacionados a las honras fúnebres",
        "Tarjetas de agradecimiento",
      ],
      price: "17,990 BOB",
      offerPrice: "15,990 BOB",
    },
  ],
};
module.exports = data;
